feature: UI/UXデザイナーの採用ページを追加
praha-inc/about-us pull request #108
Opened 2024-09-09 10:06 UTC by penpendayo

2024-09-10 07:28 UTC, shi-o-ri requested changes
やり方間違ってて手間かかる感じになってたらすみません

デザイン文化と求める人物像のところ、明日もう少し見る予定です👀

2024-09-10 07:28 UTC, shi-o-ri commented on pages/ui-ux-designer-recruit.md
> +## 仕事内容
## 仕事内容
まるっと以下にお願いします！
 - 運用中のシステムのリニューアル、エンハンス
 - 新規サービスのコンセプトづくりから設計、表層のデザイン
 - その他ビジュアル作成業務

正社員と業務委託の話は、デザイナーの欄では一旦カットで大丈夫です🙏 （プラハのHPが受託開発の話をしているので）Greenの方では一応触れようと思っていますが、基本的にデザイナーは正社員探しで考えているためです！

2024-09-10 07:28 UTC, shi-o-ri commented on pages/ui-ux-designer-recruit.md
> +TODO
### 具体的な仕事内容の一例
 - ロゴ、ピクトグラム、アイコンなどのデザインアセットの作成
 - webアプリケーションやiOS/AndroidネイティブアプリのUI作成
 - Figmaコンポーネントライブラリやスタイルの作成・運用
 - グループ会社のLP作成

2024-09-10 07:37 UTC, penpendayo commented on pages/ui-ux-designer-recruit.md
> +- 正社員の場合: 566~961万円
@shi-o-ri 
> 正社員と業務委託の金額ってどこ情報なのですか！

正社員は、シートのここ👇です！（この金額で算出されてたっぽかったので）
<img width="182" alt="スクリーンショット 2024-09-10 16 32 52" src="https://github.com/user-attachments/assets/ed740169-0958-447e-81b6-6c6cf484025e">

業務委託は、[採用ページ](https://www.praha-inc.com/recruit/designer#:~:text=%E5%B9%B4%E6%A3%92%EF%BC%9A708~900%E4%B8%87%E5%86%86%EF%BC%88%E9%80%B15%E5%8B%A4%E5%8B%99%E3%81%AE%E5%A0%B4%E5%90%88%EF%BC%89)に書いていました！

2024-09-10 07:38 UTC, penpendayo commented on pages/ui-ux-designer-recruit.md
> +- 正社員の場合: 566~961万円
たしかに固定残業代のことは書いたほうが良さそう･･。

2024-09-10 07:43 UTC, penpendayo commented on pages/ui-ux-designer-recruit.md
> +- 内定承諾後、どちらで働くか選択いただけます
@shi-o-ri 
> 方針としては正社員推しみたいなので、

そうなのですね？

これって「できれば両方欲しいけど、人が集まらないので仕方なく正社員を優先して採りたい」なのでしょうか？
もしくは「人が集まったとしても、業務委託はあんまりいらない」なのでしょうか･･？

あと、その方針って堀さんが決めてる感じなのでしょうか？
（どこでそれを知ったのか知りたいなーと思った感じです）

2024-09-11 04:17 UTC, shi-o-ri commented on pages/ui-ux-designer-recruit.md
> +  - 一緒にものづくりに挑むパートナーとしての立ち回りを期待してPrAhaに依頼するクライアントが多いからです
@penpendayo 
## 求める人物像
クライアントという言葉が受託開発前提っぽいので、一部変えたいです！
①以下の二つをトルツメ
  - 一緒にものづくりに挑むパートナーとしての立ち回りを期待してPrAhaに依頼するクライアントが多いからです
  - 我々のクライアントが置かれている状況は常に異なるので最適な解決策も(多少の傾向はあれど)異なるはずです

②以下の二つを内容変更
>   - 新規事業の開発は、やらなければいけないことが山積みです
>   - 事業を把握しているクライアントといえど、やるべきことのすべてを認識して、細かく指示を出すのは困難です
↓
 - まだまだ開発チームの人手は足りておらず、やりたいことが山積みです
 - その時々に必要なことを見つけて主体的に動く人が集まってチームができています

2024-09-11 04:17 UTC, shi-o-ri commented on pages/ui-ux-designer-recruit.md
> +## PrAhaのデザイン文化
## PrAhaのデザイン文化
まるっと以下に変更お願いします！
 - 上下関係や職種の垣根なくフラットに意見交換ができる
 - 要件を満たすためでなく、使ってくれる人にとって本当にいいものを提供するために話し合い、協力し合う
 - 主なデザインツールはFigma, コミュニケーションツールはSlack

2024-09-11 04:17 UTC, shi-o-ri commented on pages/ui-ux-designer-recruit.md
> +## PrAhaのデザイン文化
@penpendayo メンションつけ忘れ

2024-10-07 08:02 UTC, penpendayo commented on pages/ui-ux-designer-recruit.md
> +- 正社員の場合: 566~961万円
@shi-o-ri 
以下で修正しました！

[fix: 固定残業代を追記](https://github.com/praha-inc/about-us/pull/108/commits/751e54ba83f7540a1ef7312a2873af1e70a2daf9)

2024-10-07 08:02 UTC, penpendayo commented on pages/ui-ux-designer-recruit.md
> +- 正社員の場合: 566~961万円
> こんなの?追加したらどうでしょう！

載せようと思ったのですが、以下の理由からやめました🙇‍♂
- 情報量が多くなって分かりづらくなると思ったため
- 書いても双方にメリットがなさそうなため
- 「固定残業代40時間/月を含みます」とさえ書けば、「それ以上越えたらお金が払われるんだろうな〜」も自明だと思ったため

2024-10-07 08:07 UTC, penpendayo commented on pages/ui-ux-designer-recruit.md
> +## PrAhaのデザイン文化
@shi-o-ri 
以下で修正しました！

[fix: 「PrAhaのデザイン文化」をガラッと変更](https://github.com/praha-inc/about-us/pull/108/commits/cac772900686717f2962eb7d71c2253a27c874a7)

2024-10-07 08:07 UTC, penpendayo commented on pages/ui-ux-designer-recruit.md
> +## 仕事内容
@shi-o-ri 
以下で修正しました！

[fix: 「仕事内容」をガラッと変更](https://github.com/praha-inc/about-us/pull/108/commits/921c52f59fa7cd300792eb3af5c5f0bc65b26bd4)

2024-10-07 08:07 UTC, penpendayo commented on pages/ui-ux-designer-recruit.md
> +## この仕事で得られるもの
@shi-o-ri 
以下で修正しました！

[fix: 「この仕事で得られるもの」をガラっと変更](https://github.com/praha-inc/about-us/pull/108/commits/8b1b159c5f177b09e5ae3ecb8957d256e7107e98)

2024-10-07 08:07 UTC, penpendayo commented on pages/ui-ux-designer-recruit.md
> +- 内定承諾後、どちらで働くか選択いただけます
@shi-o-ri 
以下で修正しました！

[fix: 「基本的に正社員を推してます」な文言に修正](https://github.com/praha-inc/about-us/pull/108/commits/41434c26b9abbf66935be7496e7420f3156547e6)

2024-10-07 08:07 UTC, penpendayo commented on pages/ui-ux-designer-recruit.md
> +
@shi-o-ri 
以下で修正しました！

[fix: 歓迎するスキルに1つ項目を追加](https://github.com/praha-inc/about-us/pull/108/commits/7d8f29bafa28346907beebf16466f45fea5922e4)

2024-10-07 08:07 UTC, penpendayo commented on pages/ui-ux-designer-recruit.md
> +## 必須スキル
@shi-o-ri 
以下で修正しました！

[fix: 必須スキルの内容を変更](https://github.com/praha-inc/about-us/pull/108/commits/56ee701710d10a1a2ee160819662f4acdf0fe8cf)

2024-11-01 08:32 UTC, Karibash approved these changes
![LGTM](https://looks-to.me/images/posts/ia8eevont042r6b94fmj1nnv)

2024-11-01 08:34 UTC, merged