募集の追加・内容変更があったため
praha-inc/about-us pull request #6
Opened 2022-10-21 09:33 UTC by asukaaa0819

募集の追加・内容変更があったため

2022-10-21 10:30 UTC, Dowanna requested changes

2022-10-21 10:30 UTC, Dowanna commented on 採用_UI・UXデザイナーの採用要件.md
> +# WEBエンジニアの採用要件
エンジニアではなくデザイナーかな？ 🤔

2022-10-21 10:30 UTC, Dowanna commented on 採用_UI・UXデザイナーの採用要件.md
> +- [WEBエンジニアの採用要件](#web%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%81%AE%E6%8E%A1%E7%94%A8%E8%A6%81%E4%BB%B6)
エンジニアではなくデザイナーかな？ 🤔

2022-10-21 10:30 UTC, Dowanna commented on 採用_UI・UXデザイナーの採用要件.md
> +特に自分の得意領域に関することなら「こういうこともやっておいた方が良い」と提案する動きが歓迎されます
マークダウンのプレビューを見てみた方が良いかも！改行されてないと思う！ 🐬

2022-10-21 10:30 UTC, Dowanna commented on 採用_UI・UXデザイナーの採用要件.md
> +特に自分の得意領域に関することなら「こういうこともやっておいた方が良い」と提案する動きが歓迎されます
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/32860372/197174910-45c3f119-cf18-4883-a317-8e2b5d04e106.png">

こんな感じになってる

2022-10-21 10:30 UTC, Dowanna commented on 採用_WEBエンジニアの採用要件.md
> +## 必須スキル
必須スキルが重複してるかな〜 🍛

2022-10-21 10:30 UTC, Dowanna commented on 採用_WEBエンジニアの採用要件.md
> +・AWS、GCPを始めとしたクラウドインフラ使用経験
中黒じゃなくてハイフンにしておかないと箇条書きにならないよー！

2022-10-21 10:30 UTC, Dowanna commented on 採用_WEBエンジニアの採用要件.md
> +- 以下のうち1つ以上の経験
ここはハイフンいらないかな。箇条書きに含まれちゃってるから

2022-10-21 10:33 UTC, Dowanna commented
初PRありがとう〜！ ✨

2022-10-21 10:36 UTC, Dowanna commented on 採用_UI・UXデザイナーの採用要件.md
> +<!-- END doctoc generated TOC please keep comment here to allow auto update -->
あと、ここはdoctocというツールで自動生成しているTOC（目次）なんだよね。

多分エンジニアの採用要件からコピーしてきたと思うんだけど、それだとTOCの内容が乖離してしまうんだよね。TOC生成はちょいと複雑だから、今のところは選択した範囲を丸ごと消しちゃって良いよ！

2022-10-22 03:47 UTC, Dowanna commented on 採用_UI・UXデザイナーの採用要件.md
> +常に1つの手法に固執する方だと、最適な別解を見落としてしまう可能性があるからです<br>
<br>じゃなくて改行をもう一つ挟むだけで大丈夫だよ！

2022-10-24 03:13 UTC, asukaaa0819 commented on 採用_WEBエンジニアの採用要件.md
> +- 以下のうち1つ以上の経験
![image](https://user-images.githubusercontent.com/114138407/197441404-34304ab2-6c84-4f83-aee0-c70630e40ec2.png)
N1は１つ以上の経験に入らないということで、この書き方と同じように、１つ以上の経験とN１を並列に箇条書きして、経験の下に下位の箇条書きがある書き方にしました。![image](https://user-images.githubusercontent.com/114138407/197441404-34304ab2-6c84-4f83-aee0-c70630e40ec2.png)

2022-10-24 03:38 UTC, asukaaa0819 commented on 採用_WEBエンジニアの採用要件.md
> +## 必須スキル
直した結果、今度は歓迎するスキルとそのスキル内容が重複してしまっていてすみません。修正しました！

2022-10-25 06:02 UTC, Dowanna approved these changes
LGTM!

2022-10-25 06:02 UTC, merged